apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsany-paas-proxy.fullname" . }}
  labels:
    {{- include "opsany-paas-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opsany-paas-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opsany-paas-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: opsany-paas-proxy-config
              mountPath: /opt/opsany-proxy/config/prod.py
              subPath: prod.py
            - name: opsany-paas-proxy-invscript
              mountPath: /opt/opsany-proxy/invscript_proxy.py
              subPath: invscript_proxy.py
            - name: opsany-logs
              mountPath: /opt/opsany/logs
            - name: opsany-uploads
              mountPath: /opt/opsany/uploads
            - name: opsany-paas-proxy-salt-certs
              mountPath: /etc/pki/tls/certs
            - name: opsany-paas-proxy-salt-etc
              mountPath: /etc/salt/
            - name: opsany-paas-proxy-salt-cache
              mountPath: /var/cache/salt
            - name: opsany-paas-proxy-salt-srv
              mountPath: /srv/salt
            - name: opsany-paas-proxy-salt-pillar
              mountPath: /srv/pillar
            - name: opsany-paas-proxy-ansible-playbook
              mountPath: /srv/playbook
            - name: opsany-paas-proxy-ansible-pki
              mountPath: /opt/opsany/pki
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: paas-proxy
              containerPort: 8010
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: opsany-paas-proxy-config
          secret:
            secretName: opsany-paas-proxy-config
            items:
            - key: settings_production.py.proxy
              path: prod.py
        - name: opsany-paas-proxy-invscript
          secret:
            secretName: opsany-paas-proxy-invscript
            defaultMode: 0777
            items:
            - key: invscript_proxy.py
              path: invscript_proxy.py
        - name: proxy-ini
          secret:
            secretName: proxy-ini
            items:
            - key: proxy.ini
              path: proxy.ini
        - name: saltapi-ini
          secret:
            secretName: saltapi-ini
            items:
            - key: saltapi.ini
              path: saltapi.ini
        - name: saltmaster-ini
          secret:
            secretName: saltmaster-ini
            items:
            - key: saltmaster.ini
              path: saltmaster.ini
        - name: opsany-logs
          persistentVolumeClaim:
            claimName: opsany-logs
        - name: opsany-uploads
          persistentVolumeClaim:
            claimName: opsany-uploads
        - name: opsany-paas-proxy-salt-certs
          persistentVolumeClaim:
            claimName: opsany-paas-proxy-salt-certs
        - name: opsany-paas-proxy-salt-etc
          persistentVolumeClaim:
            claimName: opsany-paas-proxy-salt-etc
        - name: opsany-paas-proxy-salt-cache
          persistentVolumeClaim:
            claimName: opsany-paas-proxy-salt-cache
        - name: opsany-paas-proxy-salt-srv
          persistentVolumeClaim:
            claimName: opsany-paas-proxy-salt-srv
        - name: opsany-paas-proxy-salt-pillar
          persistentVolumeClaim:
            claimName: opsany-paas-proxy-salt-pillar
        - name: opsany-paas-proxy-ansible-playbook
          persistentVolumeClaim:
            claimName: opsany-paas-proxy-ansible-playbook
        - name: opsany-paas-proxy-ansible-pki
          persistentVolumeClaim:
            claimName: opsany-paas-proxy-ansible-pki

