apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsany-saas-workbench.fullname" . }}
  labels:
    {{- include "opsany-saas-workbench.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opsany-saas-workbench.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opsany-saas-workbench.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: opsany-saas-ce-workbench-init
              mountPath: /opt/opsany/workbench/config/__init__.py
              subPath: workbench-init.py
            - name: opsany-saas-ce-workbench-prod
              mountPath: /opt/opsany/workbench/config/prod.py
              subPath: workbench-prod.py
            - name: opsany-saas-ce-workbench-supervisor
              mountPath: /etc/supervisord.d/workbench.ini
              subPath: workbench-supervisor.ini
            - name: opsany-saas-ce-workbench-nginx
              mountPath: /etc/nginx/http.d/default.conf
              subPath: workbench-nginx.conf
            - name: opsany-saas-ce-workbench-uwsgi
              mountPath: /opt/opsany/uwsgi/workbench.ini
              subPath: workbench-uwsgi.ini
            - name: opsany-logs
              mountPath: /opt/opsany/logs
            - name: opsany-uploads
              mountPath: /opt/opsany/uploads

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /o/workbench/healthz/
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /o/workbench/healthz/
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: opsany-saas-ce-workbench-init
          configMap:
            name: opsany-saas-ce-workbench-init
            items:
            - key: workbench-init.py
              path: workbench-init.py
        - name: opsany-saas-ce-workbench-prod
          configMap:
            name: opsany-saas-ce-workbench-prod
            items:
            - key: workbench-prod.py
              path: workbench-prod.py
        - name: opsany-saas-ce-workbench-nginx
          configMap:
            name: opsany-saas-ce-workbench-nginx
            items:
            - key: workbench-nginx.conf
              path: workbench-nginx.conf
        - name: opsany-saas-ce-workbench-uwsgi
          configMap:
            name: opsany-saas-ce-workbench-uwsgi
            items:
            - key: workbench-uwsgi.ini
              path: workbench-uwsgi.ini
        - name: opsany-saas-ce-workbench-supervisor
          configMap:
            name: opsany-saas-ce-workbench-supervisor
            items:
            - key: workbench-supervisor.ini
              path: workbench-supervisor.ini
        - name: opsany-uploads
          persistentVolumeClaim:
            claimName: opsany-uploads
        - name: opsany-logs
          persistentVolumeClaim:
            claimName: opsany-logs

